Repository fralaw/rfm_stream_builder, pull requests merged in 2022-11, with the labels that each got.

#32 Modificata la query per MAX data e MIN data
  src/CustomerWindow.py
  src/DBConnector.py
  src/DataWindow.py
  src/StreamBuilder.py
Labels: enhancement, code

#35 Ottimizzazione codice
  src/CustomerWindow.py
  src/DBConnector.py
  src/DataWindow.py
  src/Day.py
  src/Example.py
  src/ExampleDictionary.py
  src/ExampleSequence.py
  src/Receipt.py
  src/Rfm.py
Labels: enhancement, code

#37 Modificato diagramma delle classi.
  resources/diagrams/Descrizione.drawio.png
  resources/diagrams/Diagramma delle Classi.drawio.png
Labels: enhancement, code

#38 REV Diagramma
  resources/diagrams/Diagramma delle Classi.drawio.png
Labels: documentation, enhancement

#39 Rivisti metodi generazione esempi e etichettatura
  src/CustomerWindow.py
  src/DBConnector.py
  src/DataWindow.py
  src/Day.py
  src/Example.py
  src/ExampleDictionary.py
  src/ExampleSequence.py
  src/Receipt.py
  src/Rfm.py
  src/RfmException.py
  src/StreamBuilder.py
  src/stream.csv
Labels: code

#40 Dataframe
  requirements.txt
  src/DataWindow.py
  src/ExampleDictionary.py
  src/ExampleSequence.py
  src/StreamBuilder.py
  src/stream.csv
Labels: enhancement, code

#41 Check finale del codice
  resources/Diagramma delle Classi.drawio.png
  src/DataWindow.py
  src/Example.py
  src/ExampleDictionary.py
  src/ExampleSequence.py
  src/StreamBuilder.py
Labels: documentation, enhancement, code

#43 Effettuati ultimi controlli + cambiamenti
  README.md
  requirements.txt
  resources/Diagramma delle Classi.drawio.png
  src/DataWindow.py
  src/Example.py
  src/ExampleDictionary.py
  src/ExampleSequence.py
  src/StreamBuilder.py
Labels: bug, documentation, enhancement, code

#46 Creato diagramma delle classi fase 2
  resources/Diagramma delle Classi 2.drawio.png
  resources/Diagramma delle Classi.drawio.png
Labels: documentation, fit/predict
